gliff-ai/annotate

src/ui.tsx

In this PR we set the paintbrush tool as the default when the app loads. We created a default tool with the selected annotation.
- [] I have commented my code, particularly in hard-to-understand areas

Set paintbrush tool as the default

---

src/annotation/index.ts
src/ui.tsx

Fixes the bug described in #35
closes #35
No
N/A
N/A

fix: Reuse empty annotation at change of active tool

---

src/ui.tsx

This is caused by IconButtons being used in a ButtonGroup which is invalid as noted [here](https://github.com/mui-org/material-ui/issues/16156#issuecomment-500853073)
This removes then and just wraps in a div.
I'll add in proper styling when we start with a style sheet etc

fix: remove Material errors

---

src/keybindings/index.ts
src/keybindings/keybindings.spec.ts
src/keybindings/keybindings.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/toolboxes/spline/index.ts
src/ui.tsx

I've added a readonly `name` field to the canvases that currently have shortcuts.
Events can then be filtered to check if they are aimed at this canvas (https://github.com/gliff-ai/annotate/pull/64/files#diff-94f3880be2d1abd06d206719935522d35557921fce534b4b9e79412c68e9ec95R417)
(It's not the optimal way, but it's the best way I could do that keeps TS happy!)

Add namespacing to keybinds

---

src/annotation/index.ts
src/keybindings/keybindings.ts
src/toolboxes/spline/Canvas.tsx
src/ui.tsx

Added event handlers in ui.tsx for cycling forwards and backwards through annotations (i.e. changing the activeAnnotationID in the annotations object, and passing this information down to the components that need it). Set up the keymappings in keybindings.ts; ctrl+rightarrow goes forward, ctrl+leftarrow goes back.
Also replaced doubleclick to close splines with a keyboard shortcut (ctrl+c).
closes #24 #47
N/A
N/A
N/A

feat: cycling annotations with ctrl+arrowkeys

---

src/store/index.ts
src/toolboxes/background/Canvas.tsx
src/toolboxes/background/Minimap.tsx
src/toolboxes/background/Store.ts
src/toolboxes/background/UI.tsx
src/toolboxes/background/configSlider.ts
src/toolboxes/background/index.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/paintbrush/Store.ts
src/toolboxes/paintbrush/UI.tsx
src/toolboxes/paintbrush/index.ts
src/toolboxes/spline/UI.tsx
src/toolboxes/spline/index.ts
src/tools.ts
src/ui.tsx

Basically added a simple State store so  toolboxes can handle and share state without it being in the UI
the simple example is BrushRadius...it's set in the Paintbrush accordion and used in the canvas, but the main UI doesn't care about it, it way just a convenient place to store it
- Created Store helper module
- Moved PB UI to toolbox, added PB radius as internal state
- Moved Spline UI to toolbox
- Moved background UI to toolbox, moved brightness and contrast to internal toolbox state.

feat: Use state store for Toolboxes

---

src/ui.tsx

It'll now keep the active tool open while still allowing others to be opened
fix #32

Fix accordion open states

---

src/toolboxes/paintbrush/Canvas.tsx

Continue to show existing paint brush layers when you create a new paintbrush layer just at low opacity, e.g. like splines.
closes (#73)
N/A
N/A
N/A

Chris baidoo/show existing paintbush layers

---

src/keybindings/keybindings.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx

Add the ability to select paintbrush or spline annotations with a single click on the annotation. When selected, an annotation becomes active and can then be modified or deleted.
For paintbrush annotations you can toggle between draw and select mode with ctrl+a (to try this out, draw multiple annotations, ctrl+a, click on existing annotations and delete, ctrl+a and draw some more..).
closes #84 
No
No
N/A

feat: Click to select annotations

---

package-lock.json
src/components/Labels.tsx
src/ui.tsx

I've moved the add object, delete object buttons into 'Layers', given they're basically the same sort of object. And moved Layers up to the top of the accordion.
Moved the load image button into the app bar.
None
None
None

feat: move the buttons around a bit

---

src/baseCanvas/Canvas.tsx
src/baseCanvas/Minimap.tsx
src/toolboxes/background/Canvas.tsx
src/toolboxes/background/Minimap.tsx
src/toolboxes/background/Store.ts
src/toolboxes/background/UI.tsx
src/toolboxes/background/drawImage.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/ui.tsx
src/upload3DImage.tsx

- Replaced `ImageData` with `ImageBitmap` throughout the code. `ImageBitmap` is like `ImageData` but renders on canvases like 40x faster, however there's no easy way to get an array of pixel data out of it, unlike with `ImageData`. This theoretically makes the app a little faster, and allows us to simplify `BackgroundCanvas` a bit because we can pass `ImageBitmap` directly into `ctx.drawImage`, unlike `ImageData` which had to go via a `HTMLCanvasElement`.
- Added support for more than 3 channels.
closes #93
No
No
N/A

feat: Use ImageBitmap and support more than 3 channels

---

src/annotation/index.ts
src/annotation/interfaces.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/ui.tsx

Adds:
- When annotating 3D images, the z-value (or slice index) gets added to the annotations object; 
- Only the annotations for the slice selected are displayed.
closes #134
No
No
N/A

fix: Single-slice drawing for 3D images

---

examples/src/index.tsx
package-lock.json
src/annotation/index.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/ui.tsx

Since we need to log every change to the `annotationsObject`, we need all changes to be done via methods on that object which can log their effects. Previously, particularly in `SplineCanvas`, we were making most of our changes by getting data structures out of `annotationsObject` by reference (e.g. `const { coordinates } = this.props.annotationsObject.getActiveAnnotation();`), and modifying them directly. If we kept doing that then we'd have to manually log all of these changes and it'd get messy and there would be bugs. So I've added a bunch of methods to the `Annotations` class like `addSplinePoint` and `addBrushStroke`, and removed methods like `getActiveAnnotation` where possible (there are a couple of methods like that that I couldn't remove, so instead I had them return a copy of a …

Annotation methods

---

.eslintrc.js
src/annotation/index.ts
tsconfig.json

As @ChasNelson1990 mentioned on Thursday, there was a lot of logging code duplication in the `Annotations` class, with `this.audit.push(...` duplicated in every set/modify method. TypeScript has experimental support for decorators (which have been in Python since 2003, just sayin), and it's apparently stable enough that people use it in production (I think Angular uses them a lot). Decorators are higher-order functions (i.e. functions that take a function and return a new function) that let you add new functionality to your functions. It's like a function that gets applied to whichever functions you choose, at compile time, to modify them in some way. So I've used them to add the logging functionality to all the set/modify methods, since so many of the guides out there use logging as an …

Using decorators for audit logging

---

src/ui.tsx

Adds a callback for saving annotations data (prop and save button). 
Note: This is part of gliff-ai/dominate#54.
No
No
N/A

chore: Add callback for saving annotations data

---

package.json

`import { UserInterface as Annotate } from '@/gliff-ai/annotate;` doesn't work. These changes seems to fix it.

fix: Module import

---

.eslintignore
src/annotation/index.ts
src/annotation/interfaces.ts
src/keybindings/keybindings.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/ui.tsx

Before we could only select splines when a spline was active, and only select brushstrokes when paintbrush was active, now click-to-select can select anything regardless of which type annotation is active (Ctrl-arrows still cycles through annotations of the same type).
Also re-wrote the code for detecting brushstroke-clicks, so it no longer gets false negatives when you click in between two widely spaced brush coordinate points (which can happen if the brushstroke was drawn with a rapid mouse movement).
Had to move some code out of SplineCanvas and PaintbrushCanvas and into the Annotations class to make this work.
closes #164

Select anything

---

src/ui.tsx

When Annotate is loaded onto Dominate, D. passes down to A. some data as props (i.e., slicesData, imageFileInfo, annotationsObject). A. should listen for changes in any of these props and update the value of the corresponding objects.
Part of gliff-ai/dominate#54

chore: Update slicesData and annotationsObject when props change

---

src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/ui.tsx

Fix bug #179, and a few other things linked to gliff-ai/dominate#54 (i.e., trigger a re-render when the prop annotationsObject changes and set activeAnnotationID for annotationsObject to the value saved as a state).
closes #179

fix: Annotate doesn't load without optional prop slicesData

---

.eslintrc.js
src/tooltips.tsx
src/ui.tsx

Added a prop which allows the app bar to be disabled. If it is, the upload/download buttons render as a toolbox like the others.
It looks like a lot more changes than it is because I also did:
```const { classes } = this.props;```
and replaces `this.props.classes` with `classes` throughout the render function, GH seems the be really struggling with the diff.

feat: optional app bar

---

src/decorators/index.tsx
src/decorators/progress.tsx
src/ui.tsx

Add decorator to stop rendering a loading spinner as soon as annotate mounts (works only when annotate is loaded onto dominate).
gliff-ai/roadmap/issues/54, full-screen spinner for page load.
No
No
No
Have any database migrations been committed as part of this pull request?

feat: Add full-screen loader

---

package.json
src/annotation/index.ts
src/components/tools.ts
src/components/tooltips.ts
src/keybindings/keybindings.ts
src/toolboxes/paintbrush/Submenu.tsx
src/toolboxes/paintbrush/index.ts
src/toolboxes/spline/Canvas.tsx
src/toolboxes/spline/Store.ts
src/toolboxes/spline/Submenu.tsx
src/toolboxes/spline/Toolbar.tsx
src/toolboxes/spline/index.ts
src/ui.tsx

1. adds a new lasso spline - basically you drag the mouse and it makes a load of points exactly where you drag (this is different to the 'magic spline' which snaps those points to areas of high gradient and is currently turned off because it works so badly)
2. a spline submenu for picking which type of spline you're using spline/magic/lasso and closing the active spline
Future work:
None
None
See above.
N/A

feat: add lasso splines

---

package-lock.json
package.json
src/annotation/index.ts
src/components/tooltips.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/paintbrush/Submenu.tsx
src/toolboxes/spline/Canvas.tsx
src/toolboxes/spline/Submenu.tsx

Users can now convert a spline to a paintbrush and fill a paintbrush strokes. Together this allows the user to use the lasso on an object and then change their mind and realise they want a painted object or just paint the edges of an object and then fill.
Note: there are some glitches to the filling algorithm. Fixing this would make a great short project for a student @BoguslawObara - the code is all open source and available for students to explore.
WILL CONVERT FROM DRAFT WHEN #271 IS MERGED AND THIS CAN BE REBASED TO MAIN.
```
"@gliff-ai/slpf": "^1.1.0",
"simplify-js": "^1.2.4",
```
Has the pipfile.lock or package-lock.json been updated? Yes
None
@philhallbio this will need to be docoumented as part of gliff-ai/document#8
N/A

feat: ability to convert splines to paintbrushes and fill paintbrush strokes

---

package-lock.json
package.json
src/Toolboxes.ts
src/toolboxes/background/Toolbar.tsx
src/toolboxes/background/Toolbox.ts
src/toolboxes/background/ToolboxMinimap.ts
src/toolboxes/background/index.ts
src/toolboxes/boundingBox/index.ts
src/toolboxes/paintbrush/Toolbar.tsx
src/toolboxes/paintbrush/index.ts
src/toolboxes/spline/Toolbar.tsx
src/toolboxes/spline/index.ts
src/tooltips/index.ts
src/ui.tsx

~~*HELP WANTED* There are two lint errors on line 237 of `src/toolboxes/background/Toolbar.tsx`. However this was copy and pasted from `src/toolboxes/paintbrush/Toolbar.tsx` where it doesn't cause an error. Any ideas?~~
Refactors the background toolbox to match the other as done in #317.
As part of this puts background settings buttons into a submenu-style toolbar. @joshuajames-smith this will need an icon, maybe something like the material 'photo' icons.
~~Currently merging into #328, will rebase when that is merged.~~
No dependency changes.
Has the pipfile.lock or package-lock.json been updated? Yes for version bump.
@philhallbio this will need to be updated in the documentation once @joshuajames-smith has helped out with icons.

feat: refactor background toolbox

---

src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/paintbrush/Store.ts
src/toolboxes/paintbrush/Toolbar.tsx
src/toolboxes/paintbrush/Toolbox.ts
src/toolboxes/paintbrush/configSlider.ts

~~*HELP WANTED* There are two lint errors on line 237 of `src/toolboxes/background/Toolbar.tsx`. However this was copy and pasted from `src/toolboxes/paintbrush/Toolbar.tsx` where it doesn't cause an error. Any ideas?~~
Adds a new button to the paintbrush toolbar (@joshuajames-smith this will need an icon) that opens two sliders - one for active and one for non-active annotation, both measured in percent.
@joshuajames-smith we need a way to label the sliders nicely because I end up with three unlabelled sliders, which isn't very helpful.
Also, @ChrisBaidoo and @joshuajames-smith aren't we meant to be able to type in the box to change the slider value? Because that doesn't work, out-the-box at least.
~~Currently merging into #318, will rebase when that is merged.~~
closes #283
No …

feat: add ability to control annotation transparency for paintbrush toolbox

---

src/download/DownloadAsTiff.tsx
src/keybindings/keybindings.ts
src/toolboxes/background/drawImage.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/paintbrush/Toolbar.tsx
src/toolboxes/paintbrush/Toolbox.ts
src/toolboxes/paintbrush/configSlider.ts
src/ui.tsx

Adds a "pixel view" button in the paintbrush toolbar. I gave up trying to optimize it to only draw new brushstrokes because it'd require a fairly complicated mechanism that wouldn't apply when annotations are deleted or the undo button is used. Fortunately it's reasonably fast drawing from scratch every time; if it becomes prohibitively slow on bigger images then I can do more optimization. 
closes https://github.com/gliff-ai/roadmap/issues/56

Pixel view

---

src/toolboxes/background/Canvas.tsx
src/toolboxes/paintbrush/Canvas.tsx

Setting `context.imageSmoothingEnabled = false` on paintbrush and background canvases. This means we see the image pixels as they really are, and the paintbrush pixels as they really are if we're in pixelview mode.

feat: sharp annotation pixels when using pixelview

---

src/toolboxes/paintbrush/Canvas.tsx

Eraser strokes are now visible as they're being drawn, not just after. Also fixed a bug where erased portions become visible with translucency when the annotation is inactive.
closes #349

Fix eraser

---

src/toolboxes/boundingBox/Canvas.tsx
src/toolboxes/spline/Canvas.tsx

Updates `annotationsObject` only once when a dragged point is released, instead of on every `onMouseMove`. Committing every mouse move meant that the audit was spammed with unnecessary actions and the undo stack regarded each mouse move as a separate action to undo, so it took a hundred undo clicks to undo a drag. Did this for both splines and bounding boxes.

Single action drag

---

src/annotation/index.ts
src/toolboxes/spline/Canvas.tsx
src/toolboxes/spline/interfaces.ts
src/ui.tsx

Instead of duplicating the first point on the end of the spline, now represents closed splines with a flag in the `Spline` interface. Ended up removing around 80 lines from spline canvas, and the undo edge cases are now fixed.
Also fixed the brush radius in `convertSpline`, removed redundant code in `fillSpline`, and fixed an edge case involving long edges in `addNewPointNearSpline`.

Closed spline flag

---

src/annotation/index.ts
src/ui.tsx

This *should* fix the Sentry error page @ChasNelson1990 and @philhallbio  were getting when loading an image with saved annotation. It's an intermittent bug that happens only when fetching the annotations object from etebase takes sufficiently long that it doesn't get passed in until after the ANNOTATE `UserInterface` constructor has already run, so would be good if people could test this one a bit before approving. I think the bounding box association was purely coincidental, since I've been able to replicate the bug without using bounding boxes and they're not involved in any mechanism I can think of for this disease state.
EDIT: I've also removed the `setActiveAnnotationID` call that was causing the bug when a new `Annotations` was passed in - it shouldn't cause the bug anymore but I …

Fix uninitialized undo

---

package-lock.json
package.json
src/annotation/index.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/paintbrush/Store.ts
src/toolboxes/paintbrush/Toolbar.tsx
src/toolboxes/paintbrush/interfaces.ts
src/ui.tsx

Adds 3D paintbrush and eraser features. Essentially the `Brush` interface now has an is3D flag (which defaults `false`) but is otherwise stored exactly the same way.
The following works:
The following does not work:
Other fixes made:
closes #430 
relates #429 #433
bugs found #426 
Has the pipfile.lock or package-lock.json been updated? Yes, as part of `npm i`
None
None. @philhallbio will need to make a new issue in DOCUMENT for this.
N/A

feat: add 3D paintbrushes

---

src/toolboxes/paintbrush/Toolbar.tsx

Use 3D Brushstrokes was named incorrectly, changed from 'brushstokes' to 'brushstrokes'

fix: amend 3D 'brushstokes' to 'brushstrokes'

---

src/toolboxes/background/Minimap.tsx

fixes bug (found by @Kinukeo) that prevents from drawing on a region near the minimap. the bug is caused by the minimap outer `div` overlapping with the `canvas` region and taking up dom space, even when the minimap is minimised.
No
No
No

fix: Cannot draw near minimap

---

src/Toolboxes.ts
src/annotation/index.ts
src/toolboxes/background/Toolbar.tsx
src/toolboxes/boundingBox/Toolbar.tsx
src/toolboxes/paintbrush/Toolbar.tsx
src/toolboxes/spline/Toolbar.tsx
src/ui.tsx

Fixes the green button highlights to work in a sensible and consistent way:
- The Paintbrush, Spline and Bounding Box buttons are highlighted if and only if the corresponding toolbox is active
- the `activeToolbox` state is now only used to specify which of Paintbrush, Spline and Bounding Box are active, this means you can have the Background toolbar open and still have Paintbrush activated and be able to draw.
- the `anchorElement` state is now used in a simpler way - it specifies which button's submenu is open, while also serving as the `anchorEl` prop for that submenu. It was kind of like this before but more explicitly so now I think. So the roles of `activeToolbox` and `anchorElement` are more clearly separated now; the former specifies which of the three annotation toolboxes is …

fix: icon highlights

---

src/annotation/index.ts
src/toolboxes/paintbrush/Canvas.tsx
src/ui.tsx

Fixes the `this.redrawUI is not a function` errors we had today. Seems the bug was also causing us to hit a react error boundary on Ctrl-Arrow; that's also fixed now.
While I was there, I found a bug in click-select where paint would be drawn on mouseUp if you selected a brushstroke, so I fixed that too.

fix: this.redrawUI is not a function

---

src/toolboxes/paintbrush/Canvas.tsx

Found a rendering bug while making the `Annotations` unit tests. To reproduce, make two or more brush annotations, activate any but the last, and use the eraser on it. The active annotation will disappear while the last one gets brighter. This was being caused by `drawWhich === "active"` not being listened for in `drawAllStrokes`.

fix: eraser disappearing

---

src/annotation/index.ts
src/toolboxes/boundingBox/Toolbar.tsx
src/ui.tsx

Fixes a bug where deleting the second annotation causes the first to disappear when they're different toolboxes.
Also fixes a bug where `activeAnnotationID` was getting set to `-1` when deleting the final annotation - not sure if it was causing any problems in practice but it's not meant to happen.
Also fixes the Bounding Box shortcut.
closes #509

fix: disappearing annotations

---

src/ui.tsx

Fixes a bug where ANNOTATE would list 3D image slices as separate channels in the channel picker. 
closes #427

fix: listing 3D image slices as separate channels

---

README.md

Tweak content.
Remove demo section (pending future addition) and use correct Github Discussions link.

docs: content tweak

---

package-lock.json
package.json
vite.config.lib.ts

As a temp fix to allow us to to use makeStyles in parent repos, hardcode the CSS prefix to "annotate" rather than the generic JSS.

fix: hack in support for makeStyles in package

---

src/index.tsx
src/toolboxes/boundingBox/interfaces.ts

This was necessary for the `makeAnnotationsJson` unit test in DOMINATE, because it turns out the `Annotation` interface doesn't actually allow for `null` coordinates for bounding boxes (which is currently how "no bounding box" is represented) when `strictNullChecks` is enabled. We have `strictNullChecks` set in DOMINATE but not in ANNOTATE, which is why this didn't cause a problem there.
Also exported the `Spline` and `BoundingBox` interfaces so I don't have to duplicate them in the unit test.

fix: explicitly allow null coords in BoundingBox interface

---

src/toolboxes/spline/Canvas.tsx
src/toolboxes/spline/Toolbar.tsx

Allows the user to place a new spline point close to the end of the existing spline; previously it would grab and shift the terminal point on mouse down if the mouse was close enough to the terminal point.
Also removes the nudge code, which shouldn't be in the base spline behaviour and I'm pretty sure was actually unreachable anyway.
Also fixes `clickNearPoint` so that it returns the nearest spline point to the mouse, rather than the first that's within 25 canvas pixels, preventing it from selecting a point that's not the closest to the mouse when points are tightly grouped.
Also prevents the user from adding a duplicate point on top of the final point if they click twice.
Also fixes an annoying console error complaining about a missing `onClickAway` handler in the spline toolbar.
Put an …

fix: spline stickiness

---

src/annotation/index.ts
src/toolboxes/spline/Canvas.tsx
src/ui.tsx

Three bug fixes:
1. Fixed `isTyping()` so it's no longer constantly returns true (was breaking all keyboard shortcuts)
2. When deleting the last annotation, a new annotation is automatically created. We automatically set the toolbox of this new annotation to be the same as the one that was deleted so it doesn't auto-change to paintbrush by default, but we needed to set `spline.isBezier` to `false` when the deleted spline was Bezier, otherwise spline store continues to say it is Bezier and the desync between annotation state and spline store breaks the toolbar logic (remember we can't access spline store in ui because it's a class component).
3. Was rendering all Bezier splines as open or closed depending on the state of the active annotation, now they're rendered correctly.
Put an `x` in …

fix: delete bezier
