gliff-ai/annotate

README.md
package.json

Adds a first version README.md and bumps the version number to 0.0.1.
closes #7
None
N/A
New README.md

feat: Add Readme.md

---

src/annotation/index.ts
src/annotation/interfaces.ts
src/baseCanvas/Canvas.tsx
src/baseCanvas/Minimap.tsx
src/toolboxes/background/Canvas.tsx
src/toolboxes/background/Minimap.tsx
src/toolboxes/background/drawImage.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/ui.tsx

Fixes the lint issues described in #40 
closes #40
None
N/A
N/A

Chas nelson1990/issue40

---

src/ui.tsx

Fixes the issue described in #23 and lint issues in ui.tsx. 
closes #23
No
N/A
N/A

fix: Zoom out only if zoomed in 

---

src/ui.tsx

Make the tool that is active colourful because it was annoying me

fix: highlight the currently active tool

---

src/components/Labels.tsx

Fix a bug in Labels.tsx: Incorrect use of useEffect in functional component.
No
N/A
N/A

fix: Incorrect use of useEffect

---

src/components/Labels.tsx
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/ui.tsx

chore: Export and import theme as a constant

---

.eslintignore
.eslintrc.js
.github/workflows/lint-build-test.yml
package-lock.json
package.json
src/annotation/index.ts
src/annotation/interfaces.ts
src/baseCanvas/Canvas.tsx
src/baseCanvas/Minimap.tsx
src/components/BaseSlider.tsx
src/components/Labels.tsx
src/configSlider.ts
src/keybindings/index.ts
src/keybindings/keybindings.spec.ts
src/toolboxes/background/Canvas.tsx
src/toolboxes/background/Minimap.tsx
src/toolboxes/background/drawImage.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/transforms.ts
src/ui.tsx

Add lint and test on push
Also lint the existing files
One of the main changes is any updates to state that use the _previous_ state are now in callbacks.
Also moved theme to it's own file rather than part of UI as that causes circular dependencies
Deps:
Adds the required ES Lint plugins to work nicely with React and TSX

Add GH actions

---

src/annotation/index.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/ui.tsx

feat: Clear annotation button

---

src/annotation/interfaces.ts
src/toolboxes/paintbrush/Canvas.tsx

Tidy the paintbrush toolbox a little.
Fix the eraser not showing while erasing
Fix the strokes not scaling when zooming
closes #71 
nope
nope
nope

Fix eraser

---

src/toolboxes/background/Canvas.tsx
src/toolboxes/background/Store.ts
src/toolboxes/background/UI.tsx

Added three checkboxes in the background toolbox for choosing which channels to display.
closes #25
N/A
N/A
N/A

Channel picker

---

src/baseCanvas/Canvas.tsx
src/toolboxes/background/configSlider.ts
src/ui.tsx

Added a material-ui slider for scrolling through image slices when a 3D image is uploaded.
closes #28
N/A
N/A
N/A

Slice slider

---

src/palette.ts
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx

Uses a consistent palette for drawing and rendering splines and brush strokes. Can easily be extended to allow switching of palettes, but just uses one for now.
closes #50 
no

Use Palette (#50)

---

src/toolboxes/paintbrush/Canvas.tsx

feat: Mark active paintbrush annotations

---

src/UploadImage.tsx
src/ui.tsx
src/upload3DImage.tsx

Add upload non-tiff images (.jpg, .jpeg, .png, .gif).
No
No
N/A

feat: Upload non-tiff images 

---

package-lock.json

build(deps): Update everything

---

.github/workflows/azure-static-web-apps-black-wave-0f4ddd903.yml
package-lock.json

Do this weeks dependabots
Stop trying to deploy dependabot PRs
Minor bumps to build tools
Nope, we'll know if I got the github actor name correctly when we merge.

skip deploy for depbot

---

package-lock.json
src/ui.tsx

All the minor dependabots, scripted PR

Dependabot batch

---

examples/index.html
src/ui.tsx

Make the container and canvas full screen
No
Handle window resize, test with zoom and pan. Move side bar elements to be floaty

Fullscreen canvas

---

src/index.tsx

Export the Annotations class so that it can be used elsewhere.

chore: Export Annotations class

---

examples/index.html
src/annotation/index.ts
src/components/Labels.tsx
src/download/DownloadAsTiff.tsx
src/tooltips.tsx
src/ui.tsx

Fixes some bugs:
closes #148
closes #141
closes #160
closes #197
closes #192
No
No
No

fix: Miscellanea

---

.github/workflows/codeql-analysis.yml

This is GitHub's own (bought) code quality and vulnerability scanner - I just want to see what it's like.

feat: add codeQL analysis

---

webpack.build.js
webpack.package.js

Fix the thing i (think i) broke yesterday
Didn't think we needed the babel config duplicated (#248). We do

fix: transpile

---

package-lock.json
package.json

build: update @gliff-ai/style

---

src/ui.tsx

This PR is part of gliff-ai/dominate/pull/275.

feat: Add prop trustedServiceButtonToolbar

---

package-lock.json
package.json
snapshots.yml

As it says on the tin!
You've all been invited to the Percy team too.

feat: add percy

---

src/index.tsx

fix: Module exports

---

src/annotation/index.ts

Adds undo functionality to bounding box and paintbrush actions.
closes #293 #294

More undoing

---

src/toolboxes/spline/Toolbar.tsx

Fix the lasso and close active spline tool
N/A
N/A
N/A
N/A

fix: make lasso tool and close active spline tool work

---

examples/index.tsx
src/ui.tsx

As it says on the tin.
No
No
No

fix: Only owners can upload images

---

package-lock.json
src/ui.tsx

fix: bump upload version, update setUploadedImage callback

---

package-lock.json
src/download/UI.tsx
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/ui.tsx

- make annotate open without `slicesData` (needed to switch between images more smoothly) 
- fix icon and tooltip
No
No
No

fix: App crashes when slicesData is undefined

---

.github/workflows/azure-static-web-apps-black-wave-0f4ddd903.yml

Adds [semantic-pull-request](https://github.com/marketplace/actions/semantic-pull-request) GitHub action to ensure that the PR title matches the [Conventional Commits spec](https://www.conventionalcommits.org/en/v1.0.0/).
No
No
No

ci: Add github action to ensure PR title follows spec

---

.github/workflows/codeql-analysis.yml

fix: make codeQL look at TS not JS

---

src/components/baseCanvas/Canvas.tsx
src/ui.tsx

fix: App bar covers image

---

src/download/UI.tsx
src/keybindings/index.ts
src/keybindings/keybindings.tsx
src/toolboxes/labels/Labels.tsx
src/toolboxes/paintbrush/Canvas.tsx
src/toolboxes/spline/Canvas.tsx
src/ui.tsx

fixed a couple of bugs in the 'annotation labels' tool.
closes #446
no
no
no

fix: Shortcuts triggered when new label is entered

---

.github/workflows/depandabot-automerge.yml

feat: add dependabot automerge Action

---

package-lock.json
package.json

trying to fix the dep conflicts that are cascading down to DOMINATE

build: update minor deps

---

index.html
src/keybindings/index.ts
src/keybindings/keybindings.spec.ts
src/keybindings/keybindings.tsx

as described. Means zoom looks pretty.

fix: prevent default of key shortcuts we override

---

src/toolboxes/background/Toolbar.tsx
src/toolboxes/labels/Submenu.tsx

Import and use theme from @gliff-ai/style to solve this issue

feat: import theme from @gliff-ai-style

---

src/components/BaseSlider.tsx

Fixes the slices slider. Turned out the fix was pretty simple, no idea why it was suddenly needed though.

fix: slices slider

---

package-lock.json
package.json

Move percy from the betas to the latest stable release. If this works we need to role this out across other repos.

feat: upgrade percy

---

src/components/baseCanvas/Canvas.tsx
src/keybindings/index.ts

fix: support cmd key on click

---

vite.config.lib.ts

build: don't bundle upload with lib

---

src/toolboxes/boundingBox/Canvas.tsx

The enhances the bounding box creation options as per a conversation about UX that @joshuajames-smith and I have had. I see no issue for it?
Previously to create a bounding box you had to click twice (TL and BR corners) but it's often expected UX to be able to drag-and-drop from TL to BR, you now can.
Also, there was a bug where if you did click and drag to create a corner there was no visual feedback and until you mouse upped, i.e. to create the TL corner you could click, drag where you wanted and release the click but you would only see the new corner on release. This is now fixed.
Local tests all pass. I expect the BS and percy tests to pass as well.
@philhallbio - this will need documenting, I have tagged it for our project board

feat: allow drag-and-drop creationg of BBs ✨

---

package-lock.json
package.json

Remove it as I don't think it's needed

build: rm chromedriver

---

package-lock.json
package.json
src/toolboxes/labels/Labels.tsx
src/toolboxes/labels/Submenu.tsx

Set width to the labels dialog and make scrollable. 
closes #763

feat: Set width to labels dialog
